# Generated by Django 4.2.16 on 2026-05-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_access_code_exam_exam_code_exam_pass_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the Blank'), ('SHORT_ANSWER', 'Short Answer'), ('IMAGE_BASED', 'Image Based')], default='MCQ', max_length=50),
        ),
    ]
