# Generated by Django 4.2.16 on 2026-05-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='certificate_template',
            field=models.CharField(choices=[('TEMPLATE_1', 'Template 1'), ('TEMPLATE_2', 'Template 2'), ('TEMPLATE_3', 'Template 3'), ('TEMPLATE_4', 'Template 4'), ('TEMPLATE_5', 'Template 5'), ('TEMPLATE_6', 'Template 6'), ('TEMPLATE_7', 'Template 7'), ('TEMPLATE_8', 'Template 8'), ('TEMPLATE_9', 'Template 9'), ('TEMPLATE_10', 'Template 10')], default='TEMPLATE_1', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='certificate_template_upload',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_unlimited_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='one_attempt_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
