# Generated by Django 4.2.16 on 2026-05-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_certificate_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.category'),
        ),
    ]
